services:
  - type: web
    name: uno-personnalise
    env: node
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: ADMIN_PASSWORD
        value: mf1979@
      - key: DATA_DIR
        value: /data
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
